language: node_js
node_js:
  - 8

cache:
  directories:
  - node_modules
  - functions/node_modules

before_install:
  - chmod +x install.sh

install:
  - ./install.sh

script:
  - npm test
  - chmod +x build.sh
  - travis_wait 40 ./build.sh

after_success:
  - chmod +x deploy.sh
  - travis_wait 50 ./deploy.sh
