language: node_js
node_js:
  - 6

cache:
  directories:
  - node_modules
  - functions/node_modules

before_install:
  - npm install codecov.io coveralls
  - chmod +x before_install.sh
  - ./before_install.sh

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - chmod +x build.sh
  - travis_wait 40 ./build.sh
  - chmod +x deploy.sh
  - travis_wait 40 ./deploy.sh
  - node node_modules/lighthouse-ci/runlighthouse.js https://react-most-wanted.com
